# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot configuration
  boot = {
    # Blacklist conflicting drivers
    blacklistedKernelModules = lib.mkDefault [ "nouveau" ];

    # Kernel modules
    kernelModules = [

      "kvm-intel"
      "tcp_bbr"
    ];

    extraModulePackages = [ ];

    # Kernel parameters
    kernel.sysctl = {
      "vm.swappiness" = 10;
      "vm.vfs_cache_pressure" = 50;
      "net.core.default_qdisc" = "fq";
      "net.ipv4.tcp_congestion_control" = "bbr";
    };

    kernelParams = [
      # Performance and I/O
      "io_delay=none"
      "iomem=relaxed"
      "rootdelay=0"

      # Security mitigations
      "mitigations=off"

      # Intel IOMMU
      "intel_iommu=on"
      "iommu=pt"

      # IRQ configuration
      "irqaffinity=0-7"
      "threadirqs"
      "nmi-watchdog=0"
      "noirqdebug"

      # NVIDIA drivers
      "nvidia-drm.modeset=1"
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1"

      # Boot display
      "quiet"
      "splash"
      "loglevel=3"
      "fbcon=nodefer"
      "logo.nologo"
      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"
      "udev.log_level=3"
      "vt.global_cursor_default=0"

      # Video and zswap
      "video.allow_duplicates=1"
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.zpool=zsmalloc"
      "zswap.max_pool_percent=10"
    ];

    # Initial ramdisk
    initrd = {
      availableKernelModules = [

        "xhci_pci"
        "ahci"
        "usbhid"
        "uas"
        "sd_mod"
        "sr_mod"
      ];
      kernelModules = [ ];
    };
  };

  # File systems
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/54b56672-3554-4442-bb08-7f7bfbead48c";
      fsType = "ext4";
      # Optimize SSD
      # ---------------------------------------------
      options = [

        "discard" # Enables the TRIM command, which allows the file system to notify the storage device of unused blocks, improving performance and longevity of solid-state drives (SSDs).
        "noatime" # Disables updating access times for files, improving file system performance by reducing write operations.

      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/43D3-786C";
      fsType = "vfat";
      options = [

        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ ];

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Hardware configuration
  hardware = {
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableAllFirmware = true;

    usb-modeswitch.enable = true;

    logitech.wireless = {
      enable = true;
      enableGraphical = true;
    };
  };
}
