# Do not modify this file! It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Boot configuration
  boot = {
    # Blacklist conflicting drivers
    blacklistedKernelModules = lib.mkDefault [ "nouveau" ];

    # Kernel modules
    kernelModules = [

      "kvm-intel"
      "tcp_bbr"
      "lz4"
    ];

    extraModulePackages = [ ];

    # Kernel parameters
    kernel.sysctl = {
      "net.core.default_qdisc" = "fq";
      "net.ipv4.tcp_congestion_control" = "bbr";
      "vm.swappiness" = 10;
      "vm.vfs_cache_pressure" = 50;

      # SSD tuning - conservative
      "vm.dirty_background_ratio" = 10;
      "vm.dirty_ratio" = 20;
      "vm.dirty_writeback_centisecs" = 300;
    };

    kernelParams = [
      # Performance and I/O
      "io_delay=none"
      "iomem=relaxed"
      "rootdelay=0"

      # Security mitigations
      "mitigations=off"

      # Intel IOMMU
      "intel_iommu=on"
      "iommu=pt"

      # IRQ configuration      
      "nmi-watchdog=0"
      "noirqdebug"

      # NVIDIA drivers
      "nvidia-drm.fbdev=1"
      "nvidia-drm.modeset=1"

      # Boot display and logging
      "quiet"
      "splash"
      "loglevel=3"
      "logo.nologo"
      "fbcon=nodefer"
      "rd.systemd.show_status=false"
      "rd.udev.log_level=3"
      "udev.log_level=3"
      "vt.global_cursor_default=0"

      # Video and zswap
      "video.allow_duplicates=1"

    ];

    # Initial ramdisk
    initrd = {
      availableKernelModules = [

        "ahci"
        "sd_mod"
        "sr_mod"
        "uas"
        "usbhid"
        "xhci_pci"
      ];
      kernelModules = [

        # early KMS and faster boot
        # Uncomment if you want faster boot-to-display and better Plymouth support
        "nvidia"
        "nvidia_drm"
        "nvidia_modeset"
        "nvidia_uvm"
      ];
    };
  };

  # File systems
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/54b56672-3554-4442-bb08-7f7bfbead48c";
      fsType = "ext4";
      # Optimize SSD
      # ---------------------------------------------
      options = [

        # "discard" # Enables the TRIM command, which allows the file system to notify the storage device of unused blocks, improving performance and longevity of solid-state drives (SSDs).
        "noatime" # Disables updating access times for files, improving file system performance by reducing write operations.

      ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/43D3-786C";
      fsType = "vfat";
      options = [

        "dmask=0077"
        "fmask=0077"
      ];
    };
  };

  swapDevices = [ ];

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Hardware configuration
  hardware = {
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableAllFirmware = true;

    usb-modeswitch.enable = true;

    logitech.wireless = {
      enable = true;
      enableGraphical = true;
    };
  };
}
