# Tolga erok
# 13 Jan 26
# docker compose for remote vscode & distro testing - no gpu needed, thats the theory

{ config, pkgs, ... }:

{
  virtualisation.docker = {
    enable = true;
    autoPrune = {
      enable = true;
      dates = "weekly";
    };
  };

  environment.systemPackages = with pkgs; [ docker-compose lazydocker ];

  users.users.tolga.extraGroups = [ "docker" ];

  # create my docker stack directory structure
  systemd.tmpfiles.rules = [
    "d /home/tolga/docker-stack 0755 tolga users -"
    "d /home/tolga/docker-stack/scripts 0755 tolga users -"
    "d /home/tolga/docker-stack/vscode-config 0755 tolga users -"
    "f /home/tolga/docker-stack/docker-compose.yml 0644 tolga users - "
    "f /home/tolga/docker-stack/prometheus.yml 0644 tolga users - "
  ];

  # write configs using environment.etc and copy to my home
  environment.etc."docker-configs/docker-compose.yml".text = ''
    # docker-compose.yml
    # # Tolga erok
    # 13 Jan 26 
    # auto-generated by nixos

    version: '3.8'

    services:
      vscode:
        image: lscr.io/linuxserver/code-server:latest
        container_name: vscode
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Australia/Perth
          - PASSWORD=ibm450
          - SUDO_PASSWORD=ibm450
        volumes:
          - ./vscode-config:/config
          - /home/tolga:/home/tolga
          - ./scripts:/scripts
        ports:
          - 8443:8443
        restart: unless-stopped

      portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        ports:
          - 9000:9000
        restart: unless-stopped

      grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
          - 3000:3000
        volumes:
          - grafana_data:/var/lib/grafana
        restart: unless-stopped

      prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
          - 9090:9090
        volumes:
          - /home/tolga/docker-stack/prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus_data:/prometheus
        restart: unless-stopped

      debian-test:
        image: debian:bookworm
        container_name: debian-test
        volumes:
          - ./scripts:/scripts
        command: sleep infinity
        restart: unless-stopped

      fedora-test:
        image: fedora:latest
        container_name: fedora-test
        volumes:
          - ./scripts:/scripts
        command: sleep infinity
        restart: unless-stopped

      arch-test:
        image: archlinux:latest
        container_name: arch-test
        volumes:
          - ./scripts:/scripts
        command: sleep infinity
        restart: unless-stopped

    volumes:
      portainer_data:
      grafana_data:
      prometheus_data:
  '';

  environment.etc."docker-configs/prometheus.yml".text = ''
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
  '';

  # copy configs to my home directory before docker-stack starts
  systemd.services.docker-stack-setup = {
    description = "copy docker configs to home directory";
    wantedBy = [ "multi-user.target" ];
    before = [ "docker-stack.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      cp /etc/docker-configs/docker-compose.yml /home/tolga/docker-stack/
      cp /etc/docker-configs/prometheus.yml /home/tolga/docker-stack/
      chown tolga:users /home/tolga/docker-stack/*.yml
    '';
  };

  # auto-start containers
  systemd.services.docker-stack = {
    description = "docker compose stack";
    after = [ "docker.service" "docker-stack-setup.service" ];
    requires = [ "docker-stack-setup.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      WorkingDirectory = "/home/tolga/docker-stack";
      ExecStart = "${pkgs.docker-compose}/bin/docker-compose up -d";
      ExecStop = "${pkgs.docker-compose}/bin/docker-compose down";
      User = "tolga";
    };
  };
}
